plugin: amazon.aws.aws_ec2
filters:
  "tag:Name": ["ansi*"]
regions:
  - us-east-1
hostnames:
  - ip-address
compose:
  ansible_user: "'ec2-user'"
  ansible_ssh_private_key_file: "'../ansible-key.pem'"
keyed_groups:
  - key: tags.Application
    separator: ''
