plugin: amazon.aws.aws_ec2
filters:
  "tag:Name": ["web_app*"]
  "tag:env": ["prod"]
regions:
  - us-east-1
hostnames:
  - private-ip-address
compose:
  ansible_user: "'ec2-user'"
  ansible_ssh_private_key_file: "'/home/ec2-user/ansible-key.pem'"
keyed_groups:
  - key: tags.Application
    separator: ''
  - key: tags.env
    separator: ''

